// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace WatcomVS.InvokeWatcom
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System.Net;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\Vii\devel\WatcomVS\WatcomVS\InvokeWatcom\ReportTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class ReportTemplate : ReportTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("<!DOCTYPE html>\r\n<html>\r\n<head>\r\n\t<title>Report: ");
            
            #line 13 "C:\Users\Vii\devel\WatcomVS\WatcomVS\InvokeWatcom\ReportTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(WebUtility.HtmlEncode(Report.Title)));
            
            #line default
            #line hidden
            this.Write(@"</title>
    <style type=""text/css"">
        .error { color: red; }
        .warning { color: orange; }
        .ok { color: black; }
        table { border: none; }
        tr {
            border-top: 1px solid black;
            border-left: none;
            border-right: none;
            border-bottom: 1px solid black;
        }
        td { border: none; }
    </style>
</head>
<body>
    <h1>Report: ");
            
            #line 29 "C:\Users\Vii\devel\WatcomVS\WatcomVS\InvokeWatcom\ReportTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(WebUtility.HtmlEncode(Report.Title)));
            
            #line default
            #line hidden
            this.Write("</h1>\r\n    <p><time datetime=\"");
            
            #line 30 "C:\Users\Vii\devel\WatcomVS\WatcomVS\InvokeWatcom\ReportTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Timestamp.ToString("O")));
            
            #line default
            #line hidden
            this.Write("\">");
            
            #line 30 "C:\Users\Vii\devel\WatcomVS\WatcomVS\InvokeWatcom\ReportTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(WebUtility.HtmlEncode(Timestamp.ToString("F"))));
            
            #line default
            #line hidden
            this.Write("</time></p>\r\n    <table>\r\n        <thead>\r\n            <tr>\r\n                <td>" +
                    "Status</td>\r\n                <td>Category</td>\r\n                <td>Description<" +
                    "/td>\r\n            </tr>\r\n        </thead>\r\n        <tbody>\r\n            ");
            
            #line 40 "C:\Users\Vii\devel\WatcomVS\WatcomVS\InvokeWatcom\ReportTemplate.tt"
 foreach(var item in Report.Items) { 
            
            #line default
            #line hidden
            this.Write("                <tr class=\"");
            
            #line 41 "C:\Users\Vii\devel\WatcomVS\WatcomVS\InvokeWatcom\ReportTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Status.ToString().ToLower()));
            
            #line default
            #line hidden
            this.Write("\">\r\n                    <td>");
            
            #line 42 "C:\Users\Vii\devel\WatcomVS\WatcomVS\InvokeWatcom\ReportTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Status.ToString()));
            
            #line default
            #line hidden
            this.Write("</td>\r\n                    <td>");
            
            #line 43 "C:\Users\Vii\devel\WatcomVS\WatcomVS\InvokeWatcom\ReportTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(WebUtility.HtmlEncode(item.Category)));
            
            #line default
            #line hidden
            this.Write("</td>\r\n                    <td>");
            
            #line 44 "C:\Users\Vii\devel\WatcomVS\WatcomVS\InvokeWatcom\ReportTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(WebUtility.HtmlEncode(item.Description)));
            
            #line default
            #line hidden
            this.Write("</td>\r\n                </tr>\r\n            ");
            
            #line 46 "C:\Users\Vii\devel\WatcomVS\WatcomVS\InvokeWatcom\ReportTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("        </tbody>\r\n    </table>\r\n</body>\r\n<html>");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "C:\Users\Vii\devel\WatcomVS\WatcomVS\InvokeWatcom\ReportTemplate.tt"

private global::WatcomVS.InvokeWatcom.Report _ReportField;

/// <summary>
/// Access the Report parameter of the template.
/// </summary>
private global::WatcomVS.InvokeWatcom.Report Report
{
    get
    {
        return this._ReportField;
    }
}

private global::System.DateTime _TimestampField;

/// <summary>
/// Access the Timestamp parameter of the template.
/// </summary>
private global::System.DateTime Timestamp
{
    get
    {
        return this._TimestampField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public virtual void Initialize()
{
    if ((this.Errors.HasErrors == false))
    {
bool ReportValueAcquired = false;
if (this.Session.ContainsKey("Report"))
{
    this._ReportField = ((global::WatcomVS.InvokeWatcom.Report)(this.Session["Report"]));
    ReportValueAcquired = true;
}
if ((ReportValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Report");
    if ((data != null))
    {
        this._ReportField = ((global::WatcomVS.InvokeWatcom.Report)(data));
    }
}
bool TimestampValueAcquired = false;
if (this.Session.ContainsKey("Timestamp"))
{
    this._TimestampField = ((global::System.DateTime)(this.Session["Timestamp"]));
    TimestampValueAcquired = true;
}
if ((TimestampValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Timestamp");
    if ((data != null))
    {
        this._TimestampField = ((global::System.DateTime)(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public class ReportTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
